### ISSUE TITLE
TypeError: "posthtml-include" is not a function

### ISSUE THREAD

**Issue by jitendravyas** [posthtml/posthtml-include#9]
```
[08:13:25] TypeError: "posthtml-include" is not a function
    at /Users/jitendra/my-projects/posthtml/gulpfile.js:8:36
    at taskWrapper (/Users/jitendra/my-projects/posthtml/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (/Users/jitendra/my-projects/posthtml/node_modules/async-done/index.js:36:18)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
```
My gulp file

```
var gulp = require('gulp');
var posthtml = require('gulp-posthtml');
var html = require('fs').readFileSync('index.html').toString();

gulp.task('posthtml', function () {
    var plugins = [
        require('posthtml-doctype')({doctype: 'HTML 5'}),
               ('posthtml-include')({ encoding: 'utf-8' })
           ];

    var options = { closingSingleTag: 'slash' };


    return gulp.src('*.html')
        .pipe(posthtml(plugins, options))
        .pipe(gulp.dest('./dest'));
});
```

**Comment by voischev** [comment]
typo?

```js
var gulp = require('gulp');
var posthtml = require('gulp-posthtml');
var html = require('fs').readFileSync('index.html').toString();

gulp.task('posthtml', function () {
    var plugins = [
               require('posthtml-doctype')({doctype: 'HTML 5'}),
               require('posthtml-include')({ encoding: 'utf-8' }) // typo require
           ];

    var options = { closingSingleTag: 'slash' };


    return gulp.src('*.html')
        .pipe(posthtml(plugins, options))
        .pipe(gulp.dest('./dest'));
});
```
